/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package files;

/**
 *
 * @author asher
 */
import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;


public class StudentInterface extends javax.swing.JFrame {

    /**
     * Creates new form StudentInterface
     */
    
    private Student student;
    private StudentManagement sm;
    private Module module;
    private ScanFile scan;
    private ArrayList<Student> allStudents;
    private ButtonGroup bg = new ButtonGroup();
    
    
    public StudentInterface() {
        initComponents();
        
        // disable editing
        studentNameDisplay.setEditable(false);
        studentClassDisplay.setEditable(false);
        adminNumberDisplay.setEditable(false);
        gpaDisplay.setEditable(false);
        
        // add the radio button filters to a button gorup
        studentSearchFilter.add(filterByClassSearch);
        studentSearchFilter.add(filterByNameSearch);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentSearchFilter = new javax.swing.ButtonGroup();
        Main = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        HomePageTopText = new javax.swing.JLabel();
        DescriptionTextPanel = new javax.swing.JPanel();
        text = new javax.swing.JLabel();
        ViewAllStudentsPanel = new javax.swing.JPanel();
        allStudentHeaderText = new javax.swing.JLabel();
        allStudentInfoDisplay = new javax.swing.JPanel();
        allStudentDisplayPanel = new javax.swing.JPanel();
        allStudDisplayName = new javax.swing.JTextField();
        allStudNameLabel = new javax.swing.JLabel();
        allStudClassDisplay = new javax.swing.JTextField();
        allStudClassLabel = new javax.swing.JLabel();
        allStudAdminNum = new javax.swing.JLabel();
        allStudAdminNumDisplay = new javax.swing.JTextField();
        allStudGPALabel = new javax.swing.JLabel();
        allStudGPADisplay = new javax.swing.JTextField();
        allStudNextBtn = new javax.swing.JButton();
        allStudPrevBtn = new javax.swing.JButton();
        allStudentModuleDisplayPanel = new javax.swing.JPanel();
        allStudModCode = new javax.swing.JTextField();
        allStudModLabel = new javax.swing.JLabel();
        allStudModName = new javax.swing.JTextField();
        allStudModNameLabel = new javax.swing.JLabel();
        alStudModMarksLabel = new javax.swing.JLabel();
        allStudModMarksDisplay = new javax.swing.JTextField();
        allStudCreditUnitLabel = new javax.swing.JLabel();
        allStudCredUnitDisplay = new javax.swing.JTextField();
        allStudModNext = new javax.swing.JButton();
        allStudModPrev = new javax.swing.JButton();
        allStudGradeLabel = new javax.swing.JLabel();
        allStudGradeDisplay = new javax.swing.JTextField();
        allStudentRefreshBtn = new javax.swing.JButton();
        allStudDisplayRemarksPanel = new javax.swing.JPanel();
        displayRemarksScrollPane = new javax.swing.JScrollPane();
        displayAllStudentsTextPaneRemarks = new javax.swing.JTextPane();
        SearchStudentsPanel = new javax.swing.JPanel();
        searchHeaderText = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        searchFilterPanel = new javax.swing.JPanel();
        filterByClassSearch = new javax.swing.JRadioButton();
        filterByNameSearch = new javax.swing.JRadioButton();
        studentSearchResults = new javax.swing.JPanel();
        studentDisplayPanel = new javax.swing.JPanel();
        studentNameDisplay = new javax.swing.JTextField();
        studentNameDisplayLabel = new javax.swing.JLabel();
        studentClassDisplay = new javax.swing.JTextField();
        studentClassDisplayLabel = new javax.swing.JLabel();
        adminNumberDisplayLabel = new javax.swing.JLabel();
        adminNumberDisplay = new javax.swing.JTextField();
        gpaDisplayLabel = new javax.swing.JLabel();
        gpaDisplay = new javax.swing.JTextField();
        nextBtn = new javax.swing.JButton();
        prevBtn = new javax.swing.JButton();
        moduleDisplayPanel = new javax.swing.JPanel();
        studentNameDisplay1 = new javax.swing.JTextField();
        studentNameDisplayLabel1 = new javax.swing.JLabel();
        studentClassDisplay1 = new javax.swing.JTextField();
        studentClassDisplayLabel1 = new javax.swing.JLabel();
        adminNumberDisplayLabel1 = new javax.swing.JLabel();
        adminNumberDisplay1 = new javax.swing.JTextField();
        gpaDisplayLabel1 = new javax.swing.JLabel();
        gpaDisplay1 = new javax.swing.JTextField();
        modCordNext = new javax.swing.JButton();
        modCordPrev = new javax.swing.JButton();
        gradeLabel = new javax.swing.JLabel();
        gradeLabelDisplay = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        searchRemarks = new javax.swing.JPanel();
        remarksScrollPane = new javax.swing.JScrollPane();
        remarksTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HomePageTopText.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        HomePageTopText.setLabelFor(HomePanel);
        HomePageTopText.setText("Welcome!");
        HomePageTopText.setMaximumSize(new java.awt.Dimension(800, 65));
        HomePageTopText.setMinimumSize(new java.awt.Dimension(800, 65));
        HomePageTopText.setPreferredSize(new java.awt.Dimension(540, 16));

        DescriptionTextPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text.setText("<html>     <p>         This program was designed using <u><strong>Apache NetBeans IDE 21</strong></u>, and coded using <u><strong>Java JDK Version 21.</strong></u>     </p>     <br>     <p>         Feel free to play around with the tabs and functions that were implemented here!     </p>     <br>     <p>         This project was done by:         <ul>             <li>Reyes Asher Benedict Calaminos DIT/FT/2B/23</li>             <li>Ng Yu Jie DIT/FT/2B/23</li>         </ul>     </p>  <p>You are currently looking at the user page.</p></html>");
        text.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout DescriptionTextPanelLayout = new javax.swing.GroupLayout(DescriptionTextPanel);
        DescriptionTextPanel.setLayout(DescriptionTextPanelLayout);
        DescriptionTextPanelLayout.setHorizontalGroup(
            DescriptionTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text)
                .addContainerGap())
        );
        DescriptionTextPanelLayout.setVerticalGroup(
            DescriptionTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomePageTopText, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(DescriptionTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomePageTopText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescriptionTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Main.addTab("Home", HomePanel);

        allStudentHeaderText.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        allStudentHeaderText.setText("View All Students");

        allStudentInfoDisplay.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Results"));

        allStudentDisplayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Student 0 out of 0"));

        allStudDisplayName.setEditable(false);

        allStudNameLabel.setText("Name");

        allStudClassDisplay.setEditable(false);
        allStudClassDisplay.setText("DCITP/FT/1A/08");
        allStudClassDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudClassDisplayActionPerformed(evt);
            }
        });

        allStudClassLabel.setText("Class");

        allStudAdminNum.setText("Admin No");

        allStudAdminNumDisplay.setEditable(false);
        allStudAdminNumDisplay.setText("2210979");
        allStudAdminNumDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudAdminNumDisplayActionPerformed(evt);
            }
        });

        allStudGPALabel.setText("GPA");

        allStudGPADisplay.setEditable(false);
        allStudGPADisplay.setText("4.0");
        allStudGPADisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudGPADisplayActionPerformed(evt);
            }
        });

        allStudNextBtn.setText("Next >");
        allStudNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudNextBtnActionPerformed(evt);
            }
        });

        allStudPrevBtn.setText("< Previous");
        allStudPrevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudPrevBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout allStudentDisplayPanelLayout = new javax.swing.GroupLayout(allStudentDisplayPanel);
        allStudentDisplayPanel.setLayout(allStudentDisplayPanelLayout);
        allStudentDisplayPanelLayout.setHorizontalGroup(
            allStudentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allStudentDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(allStudentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allStudentDisplayPanelLayout.createSequentialGroup()
                        .addGroup(allStudentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(allStudGPADisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(allStudGPALabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allStudPrevBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allStudNextBtn))
                    .addGroup(allStudentDisplayPanelLayout.createSequentialGroup()
                        .addGroup(allStudentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allStudNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allStudClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allStudDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allStudClassDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allStudAdminNum)
                            .addComponent(allStudAdminNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        allStudentDisplayPanelLayout.setVerticalGroup(
            allStudentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allStudentDisplayPanelLayout.createSequentialGroup()
                .addComponent(allStudNameLabel)
                .addGap(3, 3, 3)
                .addComponent(allStudDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allStudClassLabel)
                .addGap(3, 3, 3)
                .addComponent(allStudClassDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allStudAdminNum)
                .addGap(3, 3, 3)
                .addComponent(allStudAdminNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allStudGPALabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(allStudentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allStudentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(allStudNextBtn)
                        .addComponent(allStudPrevBtn))
                    .addComponent(allStudGPADisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        allStudentModuleDisplayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Module 0 out of 0"));

        allStudModCode.setEditable(false);
        allStudModCode.setText("ST0509");

        allStudModLabel.setText("Module Code");

        allStudModName.setEditable(false);
        allStudModName.setText("Java Programming");
        allStudModName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudModNameActionPerformed(evt);
            }
        });

        allStudModNameLabel.setText("Module Name");

        alStudModMarksLabel.setText("Marks");

        allStudModMarksDisplay.setEditable(false);
        allStudModMarksDisplay.setText("100");
        allStudModMarksDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudModMarksDisplayActionPerformed(evt);
            }
        });

        allStudCreditUnitLabel.setText("Credit Units");

        allStudCredUnitDisplay.setEditable(false);
        allStudCredUnitDisplay.setText("34");
        allStudCredUnitDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudCredUnitDisplayActionPerformed(evt);
            }
        });

        allStudModNext.setText("Next >");
        allStudModNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudModNextActionPerformed(evt);
            }
        });

        allStudModPrev.setText("< Previous");
        allStudModPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudModPrevActionPerformed(evt);
            }
        });

        allStudGradeLabel.setText("Grade");

        allStudGradeDisplay.setEditable(false);
        allStudGradeDisplay.setText("DIST");
        allStudGradeDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudGradeDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout allStudentModuleDisplayPanelLayout = new javax.swing.GroupLayout(allStudentModuleDisplayPanel);
        allStudentModuleDisplayPanel.setLayout(allStudentModuleDisplayPanelLayout);
        allStudentModuleDisplayPanelLayout.setHorizontalGroup(
            allStudentModuleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allStudentModuleDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(allStudentModuleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allStudentModuleDisplayPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(allStudModPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allStudModNext))
                    .addGroup(allStudentModuleDisplayPanelLayout.createSequentialGroup()
                        .addGroup(allStudentModuleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allStudModMarksDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(allStudentModuleDisplayPanelLayout.createSequentialGroup()
                                .addGroup(allStudentModuleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allStudModCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allStudModLabel)
                                    .addComponent(allStudModNameLabel)
                                    .addComponent(allStudModName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alStudModMarksLabel))
                                .addGap(34, 34, 34)
                                .addGroup(allStudentModuleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allStudGradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allStudCredUnitDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allStudCreditUnitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allStudGradeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        allStudentModuleDisplayPanelLayout.setVerticalGroup(
            allStudentModuleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allStudentModuleDisplayPanelLayout.createSequentialGroup()
                .addGroup(allStudentModuleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allStudentModuleDisplayPanelLayout.createSequentialGroup()
                        .addComponent(allStudModLabel)
                        .addGap(3, 3, 3)
                        .addComponent(allStudModCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allStudModNameLabel)
                        .addGap(3, 3, 3)
                        .addComponent(allStudModName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alStudModMarksLabel)
                        .addGap(3, 3, 3)
                        .addComponent(allStudModMarksDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(allStudentModuleDisplayPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(allStudCreditUnitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allStudCredUnitDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(allStudGradeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allStudGradeDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(allStudentModuleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allStudModNext)
                    .addComponent(allStudModPrev))
                .addContainerGap())
        );

        javax.swing.GroupLayout allStudentInfoDisplayLayout = new javax.swing.GroupLayout(allStudentInfoDisplay);
        allStudentInfoDisplay.setLayout(allStudentInfoDisplayLayout);
        allStudentInfoDisplayLayout.setHorizontalGroup(
            allStudentInfoDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allStudentInfoDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(allStudentInfoDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allStudentDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allStudentModuleDisplayPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        allStudentInfoDisplayLayout.setVerticalGroup(
            allStudentInfoDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allStudentInfoDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allStudentDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allStudentModuleDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        allStudentRefreshBtn.setText("Refresh");
        allStudentRefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudentRefreshBtnActionPerformed(evt);
            }
        });

        allStudDisplayRemarksPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Remarks"));

        displayAllStudentsTextPaneRemarks.setEditable(false);
        displayRemarksScrollPane.setViewportView(displayAllStudentsTextPaneRemarks);

        javax.swing.GroupLayout allStudDisplayRemarksPanelLayout = new javax.swing.GroupLayout(allStudDisplayRemarksPanel);
        allStudDisplayRemarksPanel.setLayout(allStudDisplayRemarksPanelLayout);
        allStudDisplayRemarksPanelLayout.setHorizontalGroup(
            allStudDisplayRemarksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allStudDisplayRemarksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayRemarksScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        allStudDisplayRemarksPanelLayout.setVerticalGroup(
            allStudDisplayRemarksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allStudDisplayRemarksPanelLayout.createSequentialGroup()
                .addComponent(displayRemarksScrollPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout ViewAllStudentsPanelLayout = new javax.swing.GroupLayout(ViewAllStudentsPanel);
        ViewAllStudentsPanel.setLayout(ViewAllStudentsPanelLayout);
        ViewAllStudentsPanelLayout.setHorizontalGroup(
            ViewAllStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewAllStudentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewAllStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewAllStudentsPanelLayout.createSequentialGroup()
                        .addComponent(allStudentInfoDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allStudDisplayRemarksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(ViewAllStudentsPanelLayout.createSequentialGroup()
                        .addComponent(allStudentHeaderText, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 431, Short.MAX_VALUE)
                        .addComponent(allStudentRefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        ViewAllStudentsPanelLayout.setVerticalGroup(
            ViewAllStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewAllStudentsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ViewAllStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allStudentHeaderText)
                    .addComponent(allStudentRefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewAllStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allStudentInfoDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allStudDisplayRemarksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Main.addTab("View All Students", ViewAllStudentsPanel);

        searchHeaderText.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        searchHeaderText.setText("Search");

        searchBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        searchFilterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search By Filters"));

        studentSearchFilter.add(filterByClassSearch);
        filterByClassSearch.setText("By Class");
        filterByClassSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterByClassSearchActionPerformed(evt);
            }
        });

        studentSearchFilter.add(filterByNameSearch);
        filterByNameSearch.setText("By Name");
        filterByNameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterByNameSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchFilterPanelLayout = new javax.swing.GroupLayout(searchFilterPanel);
        searchFilterPanel.setLayout(searchFilterPanelLayout);
        searchFilterPanelLayout.setHorizontalGroup(
            searchFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterByClassSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(filterByNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchFilterPanelLayout.setVerticalGroup(
            searchFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchFilterPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(searchFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterByClassSearch)
                    .addComponent(filterByNameSearch))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        studentSearchResults.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Results"));

        studentDisplayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Student 0 out of 0"));

        studentNameDisplay.setEditable(false);
        studentNameDisplay.setText("student name");

        studentNameDisplayLabel.setText("Name");

        studentClassDisplay.setEditable(false);
        studentClassDisplay.setText("DIT/FT/2B/23");
        studentClassDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentClassDisplayActionPerformed(evt);
            }
        });

        studentClassDisplayLabel.setText("Class");

        adminNumberDisplayLabel.setText("Admin No");

        adminNumberDisplay.setEditable(false);
        adminNumberDisplay.setText("2300000");
        adminNumberDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNumberDisplayActionPerformed(evt);
            }
        });

        gpaDisplayLabel.setText("GPA");

        gpaDisplay.setEditable(false);
        gpaDisplay.setText("4.0");
        gpaDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaDisplayActionPerformed(evt);
            }
        });

        nextBtn.setText("Next >");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        prevBtn.setText("< Previous");
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentDisplayPanelLayout = new javax.swing.GroupLayout(studentDisplayPanel);
        studentDisplayPanel.setLayout(studentDisplayPanelLayout);
        studentDisplayPanelLayout.setHorizontalGroup(
            studentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentDisplayPanelLayout.createSequentialGroup()
                        .addGroup(studentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentNameDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentClassDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminNumberDisplayLabel)
                            .addComponent(adminNumberDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentClassDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 208, Short.MAX_VALUE))
                    .addGroup(studentDisplayPanelLayout.createSequentialGroup()
                        .addGroup(studentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(gpaDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(gpaDisplayLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prevBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextBtn)))
                .addContainerGap())
        );
        studentDisplayPanelLayout.setVerticalGroup(
            studentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDisplayPanelLayout.createSequentialGroup()
                .addComponent(studentNameDisplayLabel)
                .addGap(3, 3, 3)
                .addComponent(studentNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentClassDisplayLabel)
                .addGap(3, 3, 3)
                .addComponent(studentClassDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminNumberDisplayLabel)
                .addGap(3, 3, 3)
                .addComponent(adminNumberDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpaDisplayLabel)
                .addGroup(studentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentDisplayPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(studentDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextBtn)
                            .addComponent(prevBtn)))
                    .addGroup(studentDisplayPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        moduleDisplayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Module 0 out of 0"));

        studentNameDisplay1.setEditable(false);
        studentNameDisplay1.setText("ST0509");

        studentNameDisplayLabel1.setText("Module Code");

        studentClassDisplay1.setEditable(false);
        studentClassDisplay1.setText("Java Programming");
        studentClassDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentClassDisplay1ActionPerformed(evt);
            }
        });

        studentClassDisplayLabel1.setText("Module Name");

        adminNumberDisplayLabel1.setText("Marks");

        adminNumberDisplay1.setEditable(false);
        adminNumberDisplay1.setText("100");
        adminNumberDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNumberDisplay1ActionPerformed(evt);
            }
        });

        gpaDisplayLabel1.setText("Credit Units");

        gpaDisplay1.setEditable(false);
        gpaDisplay1.setText("34");
        gpaDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaDisplay1ActionPerformed(evt);
            }
        });

        modCordNext.setText("Next >");
        modCordNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modCordNextActionPerformed(evt);
            }
        });

        modCordPrev.setText("< Previous");
        modCordPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modCordPrevActionPerformed(evt);
            }
        });

        gradeLabel.setText("Grade");

        gradeLabelDisplay.setEditable(false);
        gradeLabelDisplay.setText("DIST");
        gradeLabelDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeLabelDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moduleDisplayPanelLayout = new javax.swing.GroupLayout(moduleDisplayPanel);
        moduleDisplayPanel.setLayout(moduleDisplayPanelLayout);
        moduleDisplayPanelLayout.setHorizontalGroup(
            moduleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduleDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moduleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moduleDisplayPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(modCordPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modCordNext))
                    .addGroup(moduleDisplayPanelLayout.createSequentialGroup()
                        .addGroup(moduleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminNumberDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(moduleDisplayPanelLayout.createSequentialGroup()
                                .addGroup(moduleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentNameDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentNameDisplayLabel1)
                                    .addComponent(studentClassDisplayLabel1)
                                    .addComponent(studentClassDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminNumberDisplayLabel1))
                                .addGap(34, 34, 34)
                                .addGroup(moduleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gpaDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gpaDisplayLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gradeLabelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        moduleDisplayPanelLayout.setVerticalGroup(
            moduleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduleDisplayPanelLayout.createSequentialGroup()
                .addGroup(moduleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moduleDisplayPanelLayout.createSequentialGroup()
                        .addComponent(studentNameDisplayLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(studentNameDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentClassDisplayLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(studentClassDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminNumberDisplayLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(adminNumberDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(moduleDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modCordNext)
                            .addComponent(modCordPrev)))
                    .addGroup(moduleDisplayPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gpaDisplayLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gpaDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gradeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradeLabelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout studentSearchResultsLayout = new javax.swing.GroupLayout(studentSearchResults);
        studentSearchResults.setLayout(studentSearchResultsLayout);
        studentSearchResultsLayout.setHorizontalGroup(
            studentSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentSearchResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moduleDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        studentSearchResultsLayout.setVerticalGroup(
            studentSearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentSearchResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moduleDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchRemarks.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Remarks"));

        remarksTextPane.setEditable(false);
        remarksScrollPane.setViewportView(remarksTextPane);

        javax.swing.GroupLayout searchRemarksLayout = new javax.swing.GroupLayout(searchRemarks);
        searchRemarks.setLayout(searchRemarksLayout);
        searchRemarksLayout.setHorizontalGroup(
            searchRemarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchRemarksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(remarksScrollPane)
                .addContainerGap())
        );
        searchRemarksLayout.setVerticalGroup(
            searchRemarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchRemarksLayout.createSequentialGroup()
                .addComponent(remarksScrollPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout SearchStudentsPanelLayout = new javax.swing.GroupLayout(SearchStudentsPanel);
        SearchStudentsPanel.setLayout(SearchStudentsPanelLayout);
        SearchStudentsPanelLayout.setHorizontalGroup(
            SearchStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchStudentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentSearchResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchBar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SearchStudentsPanelLayout.createSequentialGroup()
                        .addGroup(SearchStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchHeaderText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchRemarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SearchStudentsPanelLayout.setVerticalGroup(
            SearchStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchStudentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SearchStudentsPanelLayout.createSequentialGroup()
                        .addComponent(searchHeaderText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBtn)
                        .addGap(6, 6, 6))
                    .addComponent(searchFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentSearchResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchRemarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Main.addTab("Search", SearchStudentsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearFields() {
    
}
    
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        // display results based on filter
        // both filters cannot be enabled in the same time
        String searchContent = searchBar.getText();
        String studentDisplayMsg = "";
        String classDisplayMsg = "";
        
        
        
        
        
    }//GEN-LAST:event_searchBtnActionPerformed
   
    private void studentClassDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentClassDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentClassDisplayActionPerformed

    private void gpaDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaDisplayActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBtnActionPerformed

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prevBtnActionPerformed

    private void studentClassDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentClassDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentClassDisplay1ActionPerformed

    private void gpaDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaDisplay1ActionPerformed

    private void modCordNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modCordNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modCordNextActionPerformed

    private void modCordPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modCordPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modCordPrevActionPerformed

    private void adminNumberDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNumberDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNumberDisplay1ActionPerformed

    private void gradeLabelDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeLabelDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeLabelDisplayActionPerformed

    private void allStudClassDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudClassDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudClassDisplayActionPerformed

    private void allStudGPADisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudGPADisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudGPADisplayActionPerformed

    private void allStudNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudNextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudNextBtnActionPerformed

    private void allStudPrevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudPrevBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudPrevBtnActionPerformed

    private void allStudModNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudModNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudModNameActionPerformed

    private void allStudModMarksDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudModMarksDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudModMarksDisplayActionPerformed

    private void allStudCredUnitDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudCredUnitDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudCredUnitDisplayActionPerformed

    private void allStudModNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudModNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudModNextActionPerformed

    private void allStudModPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudModPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudModPrevActionPerformed

    private void allStudGradeDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudGradeDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudGradeDisplayActionPerformed

    private void allStudentRefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudentRefreshBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudentRefreshBtnActionPerformed

    private void allStudAdminNumDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudAdminNumDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudAdminNumDisplayActionPerformed

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchBarActionPerformed

    private void adminNumberDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNumberDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNumberDisplayActionPerformed

    private void filterByClassSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterByClassSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterByClassSearchActionPerformed

    private void filterByNameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterByNameSearchActionPerformed
        // TODO add your handling code here:
        // filter the search by name
    }//GEN-LAST:event_filterByNameSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DescriptionTextPanel;
    private javax.swing.JLabel HomePageTopText;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JTabbedPane Main;
    private javax.swing.JPanel SearchStudentsPanel;
    private javax.swing.JPanel ViewAllStudentsPanel;
    private javax.swing.JTextField adminNumberDisplay;
    private javax.swing.JTextField adminNumberDisplay1;
    private javax.swing.JLabel adminNumberDisplayLabel;
    private javax.swing.JLabel adminNumberDisplayLabel1;
    private javax.swing.JLabel alStudModMarksLabel;
    private javax.swing.JLabel allStudAdminNum;
    private javax.swing.JTextField allStudAdminNumDisplay;
    private javax.swing.JTextField allStudClassDisplay;
    private javax.swing.JLabel allStudClassLabel;
    private javax.swing.JTextField allStudCredUnitDisplay;
    private javax.swing.JLabel allStudCreditUnitLabel;
    private javax.swing.JTextField allStudDisplayName;
    private javax.swing.JPanel allStudDisplayRemarksPanel;
    private javax.swing.JTextField allStudGPADisplay;
    private javax.swing.JLabel allStudGPALabel;
    private javax.swing.JTextField allStudGradeDisplay;
    private javax.swing.JLabel allStudGradeLabel;
    private javax.swing.JTextField allStudModCode;
    private javax.swing.JLabel allStudModLabel;
    private javax.swing.JTextField allStudModMarksDisplay;
    private javax.swing.JTextField allStudModName;
    private javax.swing.JLabel allStudModNameLabel;
    private javax.swing.JButton allStudModNext;
    private javax.swing.JButton allStudModPrev;
    private javax.swing.JLabel allStudNameLabel;
    private javax.swing.JButton allStudNextBtn;
    private javax.swing.JButton allStudPrevBtn;
    private javax.swing.JPanel allStudentDisplayPanel;
    private javax.swing.JLabel allStudentHeaderText;
    private javax.swing.JPanel allStudentInfoDisplay;
    private javax.swing.JPanel allStudentModuleDisplayPanel;
    private javax.swing.JButton allStudentRefreshBtn;
    private javax.swing.JTextPane displayAllStudentsTextPaneRemarks;
    private javax.swing.JScrollPane displayRemarksScrollPane;
    private javax.swing.JRadioButton filterByClassSearch;
    private javax.swing.JRadioButton filterByNameSearch;
    private javax.swing.JTextField gpaDisplay;
    private javax.swing.JTextField gpaDisplay1;
    private javax.swing.JLabel gpaDisplayLabel;
    private javax.swing.JLabel gpaDisplayLabel1;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JTextField gradeLabelDisplay;
    private javax.swing.JButton modCordNext;
    private javax.swing.JButton modCordPrev;
    private javax.swing.JPanel moduleDisplayPanel;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton prevBtn;
    private javax.swing.JScrollPane remarksScrollPane;
    private javax.swing.JTextPane remarksTextPane;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel searchFilterPanel;
    private javax.swing.JLabel searchHeaderText;
    private javax.swing.JPanel searchRemarks;
    private javax.swing.JTextField studentClassDisplay;
    private javax.swing.JTextField studentClassDisplay1;
    private javax.swing.JLabel studentClassDisplayLabel;
    private javax.swing.JLabel studentClassDisplayLabel1;
    private javax.swing.JPanel studentDisplayPanel;
    private javax.swing.JTextField studentNameDisplay;
    private javax.swing.JTextField studentNameDisplay1;
    private javax.swing.JLabel studentNameDisplayLabel;
    private javax.swing.JLabel studentNameDisplayLabel1;
    private javax.swing.ButtonGroup studentSearchFilter;
    private javax.swing.JPanel studentSearchResults;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
