package files;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.util.ArrayList;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class StudentManagementGui extends JFrame {
    private StudentManagement studentManagement = new StudentManagement();
    private Student selectedStudent = null;
    private ButtonGroup radioButtonGroup = new ButtonGroup();
    

     public StudentManagementGui() {
        initComponents();
        exitBtn.addActionListener(e -> {
            saveStudentsToFile();
            System.exit(0);
        });
        gpaField.setEditable(false);
        resultText.setEditable(false);
        radioButtonGroup.add(adminRadioBtn);
        radioButtonGroup.add(nameRadioBtn);
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentTxt = new javax.swing.JLabel();
        nameTxt = new javax.swing.JLabel();
        admTxt = new javax.swing.JLabel();
        classTxt = new javax.swing.JLabel();
        gpaTxt = new javax.swing.JLabel();
        moduleTxt = new javax.swing.JLabel();
        modCodeTxt = new javax.swing.JLabel();
        modNameTxt = new javax.swing.JLabel();
        marksTxt = new javax.swing.JLabel();
        creditsTxt = new javax.swing.JLabel();
        searchTxt = new javax.swing.JLabel();
        adminRadioBtn = new javax.swing.JRadioButton();
        nameRadioBtn = new javax.swing.JRadioButton();
        resultsTxt = new javax.swing.JLabel();
        createStudentBtn = new javax.swing.JButton();
        deleteStudentBtn = new javax.swing.JButton();
        addModuleBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        admField = new javax.swing.JTextField();
        classField = new javax.swing.JTextField();
        gpaField = new javax.swing.JTextField();
        modCodeField = new javax.swing.JTextField();
        modNameField = new javax.swing.JTextField();
        creditField = new javax.swing.JTextField();
        markField = new javax.swing.JTextField();
        searchField = new javax.swing.JTextField();
        resultScrollPane = new javax.swing.JScrollPane();
        resultText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("student admin system");

        studentTxt.setText("Student");

        nameTxt.setText("Name:");

        admTxt.setText("Admin:");

        classTxt.setText("Class:");

        gpaTxt.setText("GPA:");

        moduleTxt.setText("Module");

        modCodeTxt.setText("Mod Code:");

        modNameTxt.setText("Mod Name:");

        marksTxt.setText("Marks");

        creditsTxt.setText("Credit");

        searchTxt.setText("Search");

        adminRadioBtn.setText("By Admin");
        adminRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRadioBtnActionPerformed(evt);
            }
        });

        nameRadioBtn.setText("By Name");
        nameRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRadioBtnActionPerformed(evt);
            }
        });

        resultsTxt.setText("Results");

        createStudentBtn.setText("Create");
        createStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStudentBtnActionPerformed(evt);
            }
        });

        deleteStudentBtn.setText("Delete");
        deleteStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentBtnActionPerformed(evt);
            }
        });

        addModuleBtn.setText("Add");
        addModuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addModuleBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");

        resultText.setColumns(20);
        resultText.setRows(5);
        resultScrollPane.setViewportView(resultText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(admTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(creditsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(classTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gpaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(modNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 134, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(admField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(classField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gpaField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(markField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(modNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(creditField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(modCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(studentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(marksTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(modCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(moduleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createStudentBtn)
                            .addComponent(deleteStudentBtn)
                            .addComponent(addModuleBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addComponent(resultsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(adminRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nameRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(exitBtn)))
                                    .addGap(25, 25, 25)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(185, 185, 185))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(studentTxt)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt)
                    .addComponent(searchTxt)
                    .addComponent(createStudentBtn)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admTxt)
                    .addComponent(adminRadioBtn)
                    .addComponent(nameRadioBtn)
                    .addComponent(deleteStudentBtn)
                    .addComponent(admField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classTxt)
                            .addComponent(classField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gpaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(searchBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(resultsTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(moduleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(modCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addModuleBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modNameTxt)
                            .addComponent(modNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marksTxt)
                            .addComponent(markField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(creditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creditsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void createStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStudentBtnActionPerformed
    String name = nameField.getText().trim();
    String adminNumber = admField.getText().trim();
    String studentClass = classField.getText().trim();

    if (name.isEmpty() || adminNumber.isEmpty() || studentClass.isEmpty()) {
        showError("Name, Admin Number, and Class are compulsory fields!");
        return;
    }

    // Check for duplicate admin number
    for (Student student : studentManagement.getStudents()) {
        if (student.getAdminNumber().equals(adminNumber)) {
            showError("A student with this Admin Number already exists!");
            return;
              }
            }
    Student student = new Student(adminNumber, name, studentClass);
    studentManagement.getStudents().add(student);
    clearFields();
    showMessage("Student created successfully!");
    }//GEN-LAST:event_createStudentBtnActionPerformed
    
    private void deleteStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentBtnActionPerformed

        if (selectedStudent == null) {
            showError("Please search and select a student first!");
            return;
        }

        studentManagement.getStudents().remove(selectedStudent);
        clearAllFields();
        showMessage("Student deleted successfully!");
        selectedStudent = null;
    }//GEN-LAST:event_deleteStudentBtnActionPerformed

    private void addModuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addModuleBtnActionPerformed
        if (selectedStudent == null) {
        showError("Please search and select a student first!");
        return;
    }

    String code = modCodeField.getText().trim();
    String name = modNameField.getText().trim();
    String creditStr = creditField.getText().trim();
    String marksStr = markField.getText().trim();

    if (code.isEmpty() || name.isEmpty() || creditStr.isEmpty() || marksStr.isEmpty()) {
        showError("All module fields are compulsory!");
        return;
    }

    try {
        int credit = Integer.parseInt(creditStr);
        int marks = Integer.parseInt(marksStr);
        Module module = new Module(code, name, credit, marks);
        selectedStudent.addModule(module);
        selectedStudent.calculateGPA();
        gpaField.setText(String.valueOf(selectedStudent.getGPA()));
        clearModuleFields();
        showMessage("Module added successfully!");
    } catch (NumberFormatException e) {
        showError("Invalid input for Credit or Marks!");
        }
    }//GEN-LAST:event_addModuleBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchTerm = searchField.getText().trim();
        ArrayList<Student> students = studentManagement.getStudents();
        ArrayList<Student> matchingStudents = new ArrayList<>();

        for (Student student : students) {
            if ((adminRadioBtn.isSelected() && student.getAdminNumber().equals(searchTerm)) ||
                (nameRadioBtn.isSelected() && student.getName().equalsIgnoreCase(searchTerm))) {
                matchingStudents.add(student);
            }
        }

        if (matchingStudents.size() == 1) {
            // Only one student found
            selectedStudent = matchingStudents.get(0);
            displayStudent(selectedStudent);
        } else if (matchingStudents.size() > 1) {
            // Multiple students found
            String adminNumber = JOptionPane.showInputDialog(this, 
                "Multiple students found with this name. Please enter the Admin Number:");
            if (adminNumber != null && !adminNumber.trim().isEmpty()) {
                for (Student student : matchingStudents) {
                    if (student.getAdminNumber().equals(adminNumber.trim())) {
                        selectedStudent = student;
                        displayStudent(selectedStudent);
                        return;
                    }
                }
                showError("No student found with the provided Admin Number.");
            } else {
                showError("Admin Number is required to identify the student.");
            }
        } else {
            // No student found
            clearAllFields();
            resultText.setText("Student cannot be found!");
            resultScrollPane.revalidate();
            resultScrollPane.repaint();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void adminRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminRadioBtnActionPerformed

    private void nameRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameRadioBtnActionPerformed
 
        private void displayStudent(Student student) {
        nameField.setText(student.getName());
        admField.setText(student.getAdminNumber());
        classField.setText(student.getStudentClass());
        gpaField.setText(String.valueOf(student.getGPA()));
        clearModuleFields();
        resultText.setText(""); // Clear previous results
    }
    
    private void clearFields() {
        nameField.setText("");
        admField.setText("");
        classField.setText("");
        gpaField.setText("");
        clearModuleFields();
    }

    private void clearModuleFields() {
        modCodeField.setText("");
        modNameField.setText("");
        creditField.setText("");
        markField.setText("");
    }

    private void clearAllFields() {
        clearFields();
        resultText.setText("");
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);
    }

   
    
  private void saveStudentsToFile() {
    try (BufferedWriter writer = new BufferedWriter(new FileWriter("students.txt"))) {
        // Write the total number of students
        writer.write(String.valueOf(studentManagement.getStudents().size()));
        writer.newLine();

        for (Student student : studentManagement.getStudents()) {
            // Write student info
            writer.write(student.getStudentClass() + ";" +
                         student.getAdminNumber() + ";" +
                         student.getName() + ";" +
                         student.getModules().size() + ";");

            // Write module info
            for (Module module : student.getModules()) {
                writer.write(module.getModuleCode() + ";" +
                             module.getModuleName() + ";" +
                             module.getCreditUnit() + ";" +
                             module.getMarks() + ";");
            }

            // End line for current student
            writer.newLine();
        }
    } catch (IOException e) {
        showError("Failed to save student data to file.");
    }
}

   public static void main(String[] args) {
    // Ensure that GUI updates happen on the Event Dispatch Thread
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() {
            new StudentManagementGui().setVisible(true);
        }
    });
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addModuleBtn;
    private javax.swing.JTextField admField;
    private javax.swing.JLabel admTxt;
    private javax.swing.JRadioButton adminRadioBtn;
    private javax.swing.JTextField classField;
    private javax.swing.JLabel classTxt;
    private javax.swing.JButton createStudentBtn;
    private javax.swing.JTextField creditField;
    private javax.swing.JLabel creditsTxt;
    private javax.swing.JButton deleteStudentBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField gpaField;
    private javax.swing.JLabel gpaTxt;
    private javax.swing.JTextField markField;
    private javax.swing.JLabel marksTxt;
    private javax.swing.JTextField modCodeField;
    private javax.swing.JLabel modCodeTxt;
    private javax.swing.JTextField modNameField;
    private javax.swing.JLabel modNameTxt;
    private javax.swing.JLabel moduleTxt;
    private javax.swing.JTextField nameField;
    private javax.swing.JRadioButton nameRadioBtn;
    private javax.swing.JLabel nameTxt;
    private javax.swing.JScrollPane resultScrollPane;
    private javax.swing.JTextArea resultText;
    private javax.swing.JLabel resultsTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchTxt;
    private javax.swing.JLabel studentTxt;
    // End of variables declaration//GEN-END:variables
}

//